#!/bin/sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other compatible shell such as ksh or
#       bash, then change the shebang line to that shell.
#
#   (2) The slurped sed script emits newlines which sometimes get eaten up by
#       the parent shell, so adding a `true` at the end is important to ensure
#       that the correct exit status is propagated. But we can't use `;` nor could
#       we originally use that.
#
#   (3) The inline sed script, as opposed to the wrapper sh script, is useful for
#       2 reasons:
#       - Using it inline, i.e. in a Makefile, allows us to avoid bootstrapping issues
#         when using the wrapper script in check-in shell scripts such as
#         autogen.sh and can rely on a current Gradle wrapper, instead of have to
#         bootstrap our way around it.
#       - The inline script, when embedded in a Makefile, is able to strip trailing
#         carriage return and other whitespace characters that the shell script will
#         collect tripending on its invocation as part of a Makefile rule.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0
# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}	# remove leading tab and everything up to arrow
    test "$link" != "$app_path" || break # break unless symlink
    expr "x$link" : 'x\(.*\)' > /dev/null || break
    app_path=$link
done

# This is normally unused
app_base_name=${0##*/}
APP_HOME=$( cd "${app_path%"${app_path##*/}"}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != nothing to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
pw=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked for the string "unlimited".
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...sysproperties
#   * --module-path
#   * the path to the gradle jar
#   * the arguments that were passed to the gradle command

app_args=()

while [ "$#" -gt 0 ]
do
  case "$1" in
    --) shift; app_args+=( "$@" ); break ;;
    -*) app_args+=( "$1" ); shift ;;
    *) app_args+=( "$1" ); shift ;;
  esac
done

# Call the wrapper script to make sure we can execute gradle
exec "$JAVACMD" \
  ${GRADLE_OPTS} \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "${app_args[@]}"
